### ISSUE TITLE
Where to point SDK_HOME with 3.2.2?

### ISSUE THREAD

**Issue by adamtyoung** [danielsiwiec/garmin-connect-seed#7]
Total newb question but I have the SdkManager DMG that has run but have no idea where the actual SDK files are? Cheers

**Comment by andrezunido** [comment]
Hi Adam, they are in /Library/Application Support/Garmin/ConnectIQ/Sdks/
e.g.
SDK_HOME = /Users/<Your User>/Library/Application Support/Garmin/ConnectIQ/Sdks/connectiq-sdk-mac-3.2.1-2020-08-20-56ff593b7

**Comment by danielsiwiec** [comment]
Thanks for responding to the question @andrezunido . I'm closing this issue
